### ISSUE TITLE
getting some issues setting this up

### ISSUE THREAD

**Issue by SmitzyxD** [maxtheaxe/twitch-drop-farmer#2]
how do i fix this error:       Starting idling...
Traceback (most recent call last):
  File "c:\Users\User\Downloads\twitch-drop-farmer-master\farmer.py", line 329, in <module>
    bot_list = cavalry(num_bots, headless, verbose, proxy) # store the bots in a list for easy closing later
  File "c:\Users\User\Downloads\twitch-drop-farmer-master\farmer.py", line 165, in cavalry
    driver = launch(username, password, headless, verbose)
  File "c:\Users\User\Downloads\twitch-drop-farmer-master\farmer.py", line 30, in launch
    driver = start_driver(headless, proxy) # start the driver and store it (will be returned)
  File "c:\Users\User\Downloads\twitch-drop-farmer-master\farmer.py", line 57, in start_driver
    options.add_extension("Proxy Auto Auth.crx")
  File "C:\Python39\lib\site-packages\selenium\webdriver\chrome\options.py", line 131, in add_extension
    raise IOError("Path to the extension doesn't exist")
OSError: Path to the extension doesn't exist

**Comment by maxtheaxe** [comment]
Ah, this is my fault—it's throwing an error because I didn't mention that you should download the chrome extensions I'm using for proxy authentication and ad blocking. I'll add a quick check and a link to these instructions, but a _lot_ of the code should realistically be refactored at a later date.

---

**Instructions:**

* Use [CRX Downloader](https://crx-downloader.com/) to download the [ublock origin extension](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) file, rename it `ublock_origin.crx`
([here's a direct download link](https://crx-downloader.com/download?extension=https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm))
* Use [CRX Downloader](https://crx-downloader.com/) to download the [proxy auto auth extension](https://chrome.google.com/webstore/detail/proxy-auto-auth/ggmdpepbjljkkkdaklfihhngmmgmpggp) file, rename it `proxy_auto_auth.crx`
([here's a direct download link](https://crx-downloader.com/download?extension=https://chrome.google.com/webstore/detail/proxy-auto-auth/ggmdpepbjljkkkdaklfihhngmmgmpggp))
* Put both files in the same folder as everything else

---

You (@SmitzyxD) should also update/redownload the contents of this repository before doing the above steps. I'm sorry about the trouble thus far. Please let me know if you have any additional issues (honestly, I haven't tested this program particularly recently).

**Comment by SmitzyxD** [comment]
im still getting errors .   File "c:\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 78
    except TypeError:      
    ^
SyntaxError: invalid syntax

i was getting an error before that was cmd = [self.path] invalid indent then i fixed that but now this came up. cant seem to fix it

**Comment by maxtheaxe** [comment]
Can you also send the error you were having before that you fixed? You haven't changed any of the Selenium code, have you?

**Comment by SmitzyxD** [comment]
I havnt changed the slenium code. i was getting an error that was like 1 code of line that said that cmd = [self.path] File "c:\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 76 invalid indentation. i fixed it by doing  autopep8 -i "c:\Python39\lib\site-packages\selenium\webdriver\common\service.py.
 then this error came up  File "c:\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 78
except TypeError:
^
SyntaxError: invalid syntax

**Comment by maxtheaxe** [comment]
Okay, using `autopep8` does in fact alter the Selenium code. Given that Selenium is written by people far more experienced than myself (excluding the code I've personally committed to it, lol), I'm inclined to say that whatever error you're getting is probably caused by either something in my code, or a change that was made (by you, accidentally) to theirs. Thus, I believe that it may be helpful to do a clean install of everything. Here's what I would do:

- delete the local version of my repo
- clone it again, then follow my instructions from earlier regarding the extensions (the `.crx` files)
- create a new [virtual environment](https://realpython.com/python-virtual-environments-a-primer/) within the newly-cloned version of my repo (within that directory, run `python3 -m venv venv`)
- activate/enter the virtual environment (in the same terminal/cmd run `source venv/bin/activate`)
- try to run `farmer.py` and install each of the missing requirements (`pip install <missing thing>`) in that virtual environment as errors are thrown (I'm sorry, I will upload a proper requirements.txt later)
- follow along with my instructions from the [README](https://github.com/maxtheaxe/twitch-drop-farmer)

If you do all of that, we can eliminate potential modification of the Selenium library as a failure point. Please check back afterwards to let me know if that's fixed your problems.

**Comment by SmitzyxD** [comment]
Okay. I ran the farmer.py and this is what im getting.
     --- Twitch Drop Farmer by Max ---

        How many accounts do you want to idle?
        (Type it in and press Enter)

        1

        Starting idling...
Traceback (most recent call last):
  File "c:\Users\User\Desktop\twitch-drop-farmer-master\farmer.py", line 332, in <module>
    bot_list = cavalry(num_bots, headless, verbose, proxy) # store the bots in a list for easy closing later
  File "c:\Users\User\Desktop\twitch-drop-farmer-master\farmer.py", line 160, in cavalry
    username = creds[i][0] # get username from first element on each sublist
IndexError: list index out of range

and if i open the accounts creator.py this is what i get
Traceback (most recent call last):
  File "c:\Users\User\Desktop\twitch-drop-farmer-master\account-creator.py", line 276, in <module>
    create_accounts(num_accs, headless, verbose, proxy) # make new accounts, store them in global        
  File "c:\Users\User\Desktop\twitch-drop-farmer-master\account-creator.py", line 230, in create_accounts    username = creds[i][0] # get username from first element on each sublist
IndexError: list index out of range

**Comment by SmitzyxD** [comment]
Hello?

**Comment by maxtheaxe** [comment]
Apologies for the delay. If you want, I'm happy to hop on a call and help you get fully set up once and for all.
